// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfeRQRQkBJb4XaedRsO1Pm5SphqXif-kM',
    appId: '1:947447463024:web:a29f5ee603b77d79d708b5',
    messagingSenderId: '947447463024',
    projectId: 'fitness-2c8ce',
    authDomain: 'fitness-2c8ce.firebaseapp.com',
    storageBucket: 'fitness-2c8ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPvZ0KGtlVFRBTj_JrnDjqfwxL8-LaAw',
    appId: '1:947447463024:android:97fedcef7ea865edd708b5',
    messagingSenderId: '947447463024',
    projectId: 'fitness-2c8ce',
    storageBucket: 'fitness-2c8ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAte-eVGlgIsWzX-dMhIakjT2wwtCMBhdk',
    appId: '1:947447463024:ios:4b8fd3f94b248665d708b5',
    messagingSenderId: '947447463024',
    projectId: 'fitness-2c8ce',
    storageBucket: 'fitness-2c8ce.firebasestorage.app',
    iosBundleId: 'com.nduko.fitness',
  );
}
